Issue 56
underground-software/ILKD_course_materials pull request #91
Opened 2024-12-14 23:18 UTC by ealderman-uml

Add instruction to check course dashboard after submission to setup assignment.

Added a section to the setup assignment instructing students to check the
course dashboard to confirm their submission was received
after they email their patches.

Addresses issue #56

2024-12-15 22:14 UTC, charliemirabile requested changes
This one has specific alterations I would like to see, outlined in my other comment but it along with all the other PRs you made are targeting the master branch when they should be targeting 2024_fall_uml. I sent you info about changing that on matrix, but just replying here too in case you aren't looking there.

2024-12-15 22:14 UTC, charliemirabile commented on assignments/setup.md
This info is actually incorrect, the email will not show up, it only appears on dashboard (until after the deadline). I should have been clear about this problem in the related issue, but in connection with adding these correct instructions about checking the dashboard, it makes sense to remove this outdated info too.

2024-12-17 04:12 UTC, ealderman-uml commented
- Rebased my local working branch `issue_56` to `2024_fall_uml`.
- Ensured the lines you had referenced were amended.
  - It appears they had already been removed in the `2024_fall_uml` branch.
- Adjusted my phrasing to match the context of the `2024_fall_uml` branch.
- Force pushed to my fork to reflect the rebase and changes.
- Updated target branch to be `2024_fall_uml`

2024-12-20 17:15 UTC, charliemirabile approved these changes
lgtm

2024-12-20 17:15 UTC, merged